import { MonkeyPhrases } from '@components/atoms/MonkeyNotification/MonkeyNotofocation.types'
import { MONKEY_NOTIFICATION_STATUS } from '@types'

export const EN_PHRASES: Required<MonkeyPhrases> = {
  [MONKEY_NOTIFICATION_STATUS.TooLittleForWin]: [
    'Tiny nibble!',
    'Baby steps only.',
    'Add some muscle!',
    'Feed the tower!',
    'Barely a dent.',
    'Grab a bigger chunk!',
    'Banana crumbs only.',
    'We need a storm!',
    'Power up the plan!',
    'Time for a gulp!',
    'Now the reps!',
    'Make it roar!',
    'Jump a little higher!',
    'Light the fireworks!',
    'Swing again!',
    'Shake the branches!',
    'Bring a shovel!',
    'Hammer time!',
    'Dive deeper!',
    'We need a bang!',
    'Add some drama!',
    'Bring the hot lava!',
    'Build a brick!',
    'We need a stare!',
    'Roll the full movie!',
    'We need an avalanche!',
    'We need a tsunami!',
    'Try a shove!',
    'Tower wants more!',
    'Make it louder!',
    'Monkey wants cake!',
    'Goal needs a punch!',
    'Call the storm!',
    'Leave a scar!',
    'We need a boulder!',
    'Wake the monkey up!',
    'Flood it more!',
    'We need a shout!',
    'Scratched the bark.',
    'Jungle needs fire!',
    'Jungle is thirsty!',
    'Push a bit harder!',
    'Keep going, more!',
    'Try again, bigger!',
    'Give it more juice!',
  ],

  [MONKEY_NOTIFICATION_STATUS.TooMuchForWin]: [
    'Banana tsunami!',
    'Easy, champ!',
    'Overkill alert!',
    'Trim the jungle!',
    'Too spicy, cool down!',
    'Past Mars, turn back!',
    'Big swing, easy now!',
    'Save some bananas!',
    'Grab a towel!',
    'Elephant step, oops!',
    'Reel it in!',
    'Use a teacup!',
    'Cannon for ants!',
    'Dial it to medium!',
    'We needed a drone!',
    'Lower the volume!',
    'Glide back down!',
    'Ease the throttle!',
    'We asked for two!',
    'Trim the top!',
    'Balance the mix!',
    'We needed a sip!',
    'We planned a snack!',
    'Oops, sledgehammer!',
    'Goal is behind us!',
    'Boss damage, oops!',
    'Close half the gate!',
    'Past the finish line!',
    'Tap the brakes!',
    'Less is more today!',
    'Precision, not boom!',
    'Banana bomb, oops!',
    'Tower can’t chew that!',
    'Smashed with a planet!',
    'Needed one snowflake!',
    'Calm the jungle down!',
    'Goal wanted a nibble!',
    'Banana volcano erupted!',
    'Tower’s dizzy now!',
    'Jungle feast, oops!',
    'Needed a purr!',
    'Wanted a pat!',
    'Thunder at a picnic!',
    'Tower burped!',
    'Less drama, please!',
  ],

  [MONKEY_NOTIFICATION_STATUS.CloseToWin]: [
    'So close!',
    'Almost there!',
    'One step more!',
    'Don’t blink now!',
    'Final stretch!',
    'Reach out!',
    'Balance it now!',
    'Nudge, don’t shove!',
    'Turn it gently!',
    'Tiny polish left!',
    'One more bite!',
    'Toes on the line!',
    'Place it precisely!',
    'We’re golden!',
    'Triumph is near!',
    'Careful now!',
    'Feather-light touch!',
    'Nearly done!',
    'Seals the deal!',
    'Stay centered!',
    'One leaf more!',
    'Final micro step!',
    'Align gently!',
    'Smell confetti!',
    'Slide, don’t push!',
    'Thread the needle!',
    'One piece missing!',
    'Easy does it!',
    'Serve it up!',
    'One precise nudge!',
    'Don’t slip now!',
    'One hair from glory!',
    'Final whisper!',
    'Goal’s breathing near!',
    'Confetti loading...',
    'Leans toward victory!',
    'Polish the crown!',
    'Like banana to peel!',
    'One sneeze away!',
    'Tail away from win!',
    'Don’t tremble now!',
    'Finish line smiles!',
    'One more step, legends!',
    'Just sprinkle sugar!',
    'Victory smells close!',
  ],

  [MONKEY_NOTIFICATION_STATUS.Neutral]: [
    'Good pace!',
    'Nice flow!',
    'Steady climb!',
    'Learning the mood!',
    'Solid move!',
    'Measure, proceed!',
    'Strategy continues!',
    'Observe and adapt!',
    'Think before leap!',
    'Patterns emerging!',
    'Map the next route!',
    'Tune the decision!',
    'Set the next stone!',
    'Options stay open!',
    'Make a wiser guess!',
    'Listen, then act!',
    'Save energy, push!',
    'Plot the follow-up!',
    'Avoid noisy moves!',
    'Trim rough edges!',
    'Opportunity will wink!',
    'Prepare the thrust!',
    'Patience earns gains!',
    'Keep hands nimble!',
    'Play it methodical!',
    'Space to improve!',
    'Next one matters!',
    'Captain, carry on!',
    'Choose wisely next!',
    'Proceed with care!',
    'Keep the rhythm!',
    'Just flow!',
    'Monkey hums calmly!',
    'Row on!',
    'Breathe and play!',
    'Gears turning smooth!',
    'Tail swinging evenly!',
    'Patterns await!',
    'Patience pays!',
    'Tower listens!',
    'Monkey meditates!',
    'Not hot, not cold!',
    'Step forward next!',
    'Clouds may form!',
    'Path is clear!',
  ],
}
