import { MonkeyPhrases } from '@components/atoms/MonkeyNotification/MonkeyNotofocation.types'
import { MONKEY_NOTIFICATION_STATUS } from '@types'

export const EN_PHRASES: Required<MonkeyPhrases> = {
  [MONKEY_NOTIFICATION_STATUS.TooLittleForWin]: [
    'Tiny nibble. We need bigger bites.',
    'Baby steps. Grab a larger chunk.',
    'Too light. Add some monkey muscle.',
    'Not enough. Feed the hungry tower.',
    'Small move. The goal is still yawning.',
    'That tickled. Push a bit harder.',
    'We sneezed, not scored. Go on.',
    'Banana crumbs. We need the bunch.',
    'Gentle breeze. We need a storm.',
    'Cute attempt. Power up the plan.',
    'Low fuel. Pour more into it.',
    'Sips only. Time for a gulp.',
    'Warm-up at best. Now the reps.',
    'Still stretching. Start the sprint.',
    'Just a whisper. Make it roar.',
    'Soft footprint. Jump a little higher.',
    'Tiny spark. Light the fireworks.',
    'Barely a dent. Swing again.',
    'Quiet step. Shake the branches.',
    'Teaspoon move. Bring a shovel.',
    'Feather touch. Hammer is needed.',
    'Skimming the surface. Dive deeper.',
    'A ping. We need a bang.',
    'The needle barely moved.',
    'Monkey yawns. Add some drama.',
    'Warm air. We need hot lava.',
    'Speck of dust. Build a brick.',
    'A wink. We need a stare.',
    'Trailer only. Roll the full movie.',
    'Snowflake. We need an avalanche.',
    'Tiny wave. We need a tsunami.',
    'Flick only. Try a shove.',
    'Baby banana bite. Hungry tower wants more.',
    'Echo, not thunder. Make it louder.',
    'Just crumbs. Monkey wants cake.',
    'You poked. Goal needs a punch.',
    'Soft breeze. Call the storm.',
    'Scratch mark. Leave a scar.',
    'A pebble. We need a boulder.',
    'Monkey still napping. Wake it up.',
    'Gentle drip. Flood it more.',
    'Whisper move. We need a shout.',
    'Barely scratched the bark.',
    'Tiny spark. Jungle needs fire.',
    'Small sip. Jungle is still thirsty.',
  ],

  [MONKEY_NOTIFICATION_STATUS.TooMuchForWin]: [
    'Whoa! That’s a banana tsunami.',
    'Easy, champ. The scale exploded.',
    'Overkill alert. Trim the jungle.',
    'Too spicy. Cool the recipe down.',
    'We launched past Mars. Turn back.',
    'Big swing! The tree is shaking.',
    'Too generous. Save some bananas.',
    'We flooded it. Grab a towel.',
    'Elephant step. We needed a hop.',
    'Over the line. Reel it in.',
    'Firehose mode. Use a teacup.',
    'We used a cannon for ants.',
    'Mega boost. Dial it to medium.',
    'Rocket launch. We needed a drone.',
    'Max volume. Lower the monkey mic.',
    'Overshot the nest. Glide back.',
    'Supercharge engaged. Ease the throttle.',
    'Banana truck? We asked for two.',
    'Too tall. Trim the top branches.',
    'Hype overload. Balance the mix.',
    'Ocean poured. We needed a sip.',
    'Full feast. We planned a snack.',
    'Sledgehammer meet peanut. Oops.',
    'The goal waved from behind us.',
    'Boss battle damage on a minion.',
    'A floodgate opened. Close half.',
    'We sprinted past the finish line.',
    'Turbo mode. Tap the brakes.',
    'Monkey says “Less is more” today.',
    'Precision, not explosion, my friend.',
    'Banana bomb dropped. Oops.',
    'Overstuffed. Tower can’t chew that.',
    'We smashed a nut with a planet.',
    'Banana blizzard. We needed one snowflake.',
    'Jungle shook too hard. Calm it down.',
    'Monster bite. Goal asked for a nibble.',
    'Banana volcano erupted!',
    'Overjump. Tower’s dizzy now.',
    'Jungle feast instead of a snack.',
    'That was a lion’s roar. Needed a purr.',
    'Elephant hug. We wanted a pat.',
    'You brought a thunderstorm to a picnic.',
    'Banana overload! Tower burped.',
    'Too much spice. Dish exploded.',
    'Monkey says: next time, less drama.',
  ],

  [MONKEY_NOTIFICATION_STATUS.CloseToWin]: [
    'So close! One crisp step more.',
    'Almost there. Keep the rhythm steady.',
    'Victory is sniffing our bananas.',
    'Edge of glory. Don’t blink now.',
    'Final stretch. Smooth and steady.',
    'The goal is waving. Reach out.',
    'One pebble more to balance it.',
    'Tight margin. Nudge, don’t shove.',
    'The lock clicks. Turn it gently.',
    'Almost perfect. Tiny polish left.',
    'We taste the win. One bite.',
    'Finishing line hugs our toes.',
    'Don’t rush. Place it precisely.',
    'Little tweak and we’re golden.',
    'Monkey senses triumph in the air.',
    'Within whiskers. Careful now.',
    'Aim true. Feather-light adjustment.',
    'Careful now, champion. Nearly done.',
    'Whisper move seals the deal.',
    'Balance beam vibes—stay centered.',
    'Just a leaf more on the pile.',
    'Edge secured. Final micro step.',
    'Win radar beeping. Align gently.',
    'Close enough to smell confetti.',
    'Tight window. Slide, don’t push.',
    'Steady paws. Thread the needle.',
    'The puzzle misses one small piece.',
    'Fine-tune mode: on. Easy does it.',
    'Finish flavor detected. Serve it.',
    'One precise nudge to glory.',
    'Banana in sight. Don’t slip.',
    'One hair away from glory.',
    'Final whisper and it’s done.',
    'Goal is breathing down our neck.',
    'Confetti loading… almost.',
    'Tower leans toward victory.',
    'Just polish the crown.',
    'Close, like banana to peel.',
    'One sneeze from success.',
    'Monkey tail away from win.',
    'Don’t tremble—one more step.',
    'Finish line is smiling.',
    'Micro-step and we’re legends.',
    'Almost baked. Just sprinkle sugar.',
    'Banana smell is strong—victory close.',
  ],

  [MONKEY_NOTIFICATION_STATUS.Neutral]: [
    'Good pace. Keep playing your plan.',
    'Nice flow. Read the board calmly.',
    'Steady climb. Watch the next step.',
    'We’re learning the tower’s mood.',
    'Solid move. Eyes on the target.',
    'Balanced vibes. Measure and proceed.',
    'Monkey approves. Strategy continues.',
    'All right. Observe and adapt smartly.',
    'Tempo is fine. Think before leap.',
    'Keep cool. Patterns are emerging.',
    'Cruising along. Map the next route.',
    'Not bad. Tune the next decision.',
    'Calm river. Set the next stone.',
    'Neutral ground. Options stay open.',
    'Data in. Make a wiser guess.',
    'Board whispers. Listen, then act.',
    'Good read. Save energy for push.',
    'Stable step. Plot the follow-up.',
    'We’re fine. Avoid noisy moves.',
    'Momentum steady. Trim rough edges.',
    'Keep scanning. Opportunity will wink.',
    'Baseline set. Prepare the thrust.',
    'Middle lane. Patience earns gains.',
    'Neat choice. Keep hands nimble.',
    'Signals mixed. Play it methodical.',
    'Okay shape. Space for improvement.',
    'Calibrate. The next one matters.',
    'Systems nominal. Captain, carry on.',
    'All green-ish. Choose wisely next.',
    'Monkey nods. Proceed with care.',
    'Balanced jungle. Keep rhythm.',
    'Neither win nor loss. Just flow.',
    'Monkey hums calmly.',
    'Still waters. Row on.',
    'Game steady. Breathe and play.',
    'All gears turning smooth.',
    'Monkey tail swinging evenly.',
    'Calm board. Patterns await.',
    'Middle ground. Patience pays.',
    'No rush. Tower listens.',
    'Monkey meditates. Join him.',
    'Not hot, not cold. Just right.',
    'Base stable. Step forward next.',
    'Neutral sky. Clouds may form.',
    'Banana path is clear, but long.',
  ],
}
