import { CAFlagIcon, USAFlagIcon } from '@assets/icons/flags'
import { Country, LEVEL_DIFFICULTY, LevelConfig, LevelId } from '@types'

export const TOTAL_LEVELS = 30
export const LEVEL_CARD_WIDTH = 200
export const LEVEL_CARD_GAP = 20

export const LEVEL_CONFIG: Record<LevelId, LevelConfig> = {
  1: {
    fistTower: {
      start: 8,
      end: 15,
      fortuneWheelData: ['x8', 'x15', 'x10', 'x9', 'x12', 'x13', 'x11', 'x14'],
    },
    secondTower: {
      start: 1,
      end: 3,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 5,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 20,
    attempts: 5,
    difficulty: LEVEL_DIFFICULTY.Easy,
  },
  2: {
    fistTower: {
      start: 8,
      end: 15,
      fortuneWheelData: [
        'x8',
        'x15',
        'x11',
        'x14',
        'x10',
        'x9',
        'x12',
        'x13',
        'x16',
      ],
    },
    secondTower: {
      start: 1,
      end: 3,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 5,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 22,
    attempts: 5,
    difficulty: LEVEL_DIFFICULTY.Easy,
  },
  3: {
    fistTower: {
      start: 8,
      end: 16,
      fortuneWheelData: [
        'x12',
        'x13',
        'x16',
        'x8',
        'x15',
        'x11',
        'x14',
        'x10',
        'x9',
      ],
    },
    secondTower: {
      start: 1,
      end: 4,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 6,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 24,
    attempts: 5,
    difficulty: LEVEL_DIFFICULTY.Easy,
  },
  4: {
    fistTower: {
      start: 8,
      end: 16,
      fortuneWheelData: [
        'x11',
        'x14',
        'x10',
        'x9',
        'x12',
        'x13',
        'x16',
        'x8',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 4,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 6,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 26,
    attempts: 5,
    difficulty: LEVEL_DIFFICULTY.Easy,
  },
  5: {
    fistTower: {
      start: 9,
      end: 17,
      fortuneWheelData: [
        'x9',
        'x12',
        'x13',
        'x16',
        'x17',
        'x11',
        'x14',
        'x10',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 5,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 6,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 28,
    attempts: 5,
    difficulty: LEVEL_DIFFICULTY.Easy,
  },
  6: {
    fistTower: {
      start: 9,
      end: 17,
      fortuneWheelData: [
        'x13',
        'x16',
        'x17',
        'x11',
        'x14',
        'x9',
        'x12',
        'x10',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 5,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 6,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 29,
    attempts: 5,
    difficulty: LEVEL_DIFFICULTY.Easy,
  },
  7: {
    fistTower: {
      start: 10,
      end: 18,
      fortuneWheelData: [
        'x17',
        'x11',
        'x14',
        'x18',
        'x13',
        'x16',
        'x12',
        'x10',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 5,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 6,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 28,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Easy,
  },
  8: {
    fistTower: {
      start: 10,
      end: 18,
      fortuneWheelData: [
        'x12',
        'x17',
        'x11',
        'x14',
        'x18',
        'x13',
        'x16',
        'x10',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 5,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 6,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 30,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Easy,
  },
  9: {
    fistTower: {
      start: 11,
      end: 19,
      fortuneWheelData: [
        'x12',
        'x17',
        'x19',
        'x11',
        'x14',
        'x18',
        'x13',
        'x16',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 4,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 6,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 32,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Easy,
  },
  10: {
    fistTower: {
      start: 11,
      end: 19,
      fortuneWheelData: [
        'x14',
        'x18',
        'x12',
        'x17',
        'x19',
        'x11',
        'x13',
        'x16',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 4,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 7,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 34,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Easy,
  },
  11: {
    fistTower: {
      start: 12,
      end: 20,
      fortuneWheelData: [
        'x18',
        'x12',
        'x17',
        'x19',
        'x14',
        'x20',
        'x13',
        'x16',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 5,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 7,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 36,
    attempts: 5,
    difficulty: LEVEL_DIFFICULTY.Medium,
  },
  12: {
    fistTower: {
      start: 12,
      end: 20,
      fortuneWheelData: [
        'x17',
        'x19',
        'x14',
        'x20',
        'x18',
        'x12',
        'x13',
        'x16',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 5,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 7,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 38,
    attempts: 5,
    difficulty: LEVEL_DIFFICULTY.Medium,
  },
  13: {
    fistTower: {
      start: 13,
      end: 21,
      fortuneWheelData: [
        'x20',
        'x18',
        'x21',
        'x13',
        'x17',
        'x19',
        'x14',
        'x16',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 5,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 8,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 40,
    attempts: 5,
    difficulty: LEVEL_DIFFICULTY.Medium,
  },
  14: {
    fistTower: {
      start: 13,
      end: 21,
      fortuneWheelData: [
        'x20',
        'x21',
        'x13',
        'x17',
        'x19',
        'x18',
        'x14',
        'x16',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 5,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 8,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 42,
    attempts: 5,
    difficulty: LEVEL_DIFFICULTY.Medium,
  },
  15: {
    fistTower: {
      start: 14,
      end: 22,
      fortuneWheelData: [
        'x17',
        'x19',
        'x18',
        'x14',
        'x20',
        'x21',
        'x22',
        'x16',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 5,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 9,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 44,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Medium,
  },
  16: {
    fistTower: {
      start: 14,
      end: 22,
      fortuneWheelData: [
        'x19',
        'x18',
        'x14',
        'x20',
        'x21',
        'x17',
        'x22',
        'x16',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 5,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5'],
    },
    simpleOperators: {
      start: 1,
      end: 9,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 46,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Medium,
  },
  17: {
    fistTower: {
      start: 15,
      end: 23,
      fortuneWheelData: [
        'x23',
        'x20',
        'x21',
        'x17',
        'x22',
        'x19',
        'x18',
        'x16',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 6,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 1,
      end: 10,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 48,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Medium,
  },
  18: {
    fistTower: {
      start: 15,
      end: 23,
      fortuneWheelData: [
        'x21',
        'x17',
        'x22',
        'x19',
        'x23',
        'x20',
        'x18',
        'x16',
        'x15',
      ],
    },
    secondTower: {
      start: 1,
      end: 6,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 1,
      end: 10,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 50,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Medium,
  },
  19: {
    fistTower: {
      start: 16,
      end: 24,
      fortuneWheelData: [
        'x23',
        'x20',
        'x18',
        'x16',
        'x24',
        'x21',
        'x17',
        'x22',
        'x19',
      ],
    },
    secondTower: {
      start: 1,
      end: 6,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 1,
      end: 10,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 52,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Medium,
  },
  20: {
    fistTower: {
      start: 16,
      end: 24,
      fortuneWheelData: [
        'x21',
        'x17',
        'x23',
        'x20',
        'x18',
        'x16',
        'x24',
        'x22',
        'x19',
      ],
    },
    secondTower: {
      start: 1,
      end: 6,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 1,
      end: 10,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 54,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Medium,
  },
  21: {
    fistTower: {
      start: 17,
      end: 25,
      fortuneWheelData: [
        'x21',
        'x20',
        'x18',
        'x25',
        'x24',
        'x17',
        'x23',
        'x22',
        'x19',
      ],
    },
    secondTower: {
      start: 2,
      end: 6,
      fortuneWheelData: ['x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 1,
      end: 10,
    },
    multiplicativeOperators: {
      start: 2,
      end: 4,
    },
    prize: 56,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Hard,
  },
  22: {
    fistTower: {
      start: 17,
      end: 25,
      fortuneWheelData: [
        'x18',
        'x25',
        'x24',
        'x17',
        'x21',
        'x20',
        'x23',
        'x22',
        'x19',
      ],
    },
    secondTower: {
      start: 2,
      end: 6,
      fortuneWheelData: ['x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 2,
      end: 10,
    },
    multiplicativeOperators: {
      start: 2,
      end: 3,
    },
    prize: 58,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Hard,
  },
  23: {
    fistTower: {
      start: 18,
      end: 26,
      fortuneWheelData: [
        'x25',
        'x24',
        'x26',
        'x21',
        'x18',
        'x20',
        'x23',
        'x22',
        'x19',
      ],
    },
    secondTower: {
      start: 2,
      end: 6,
      fortuneWheelData: ['x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 3,
      end: 11,
    },
    multiplicativeOperators: {
      start: 2,
      end: 4,
    },
    prize: 60,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Hard,
  },
  24: {
    fistTower: {
      start: 18,
      end: 26,
      fortuneWheelData: [
        'x24',
        'x26',
        'x21',
        'x18',
        'x25',
        'x20',
        'x23',
        'x22',
        'x19',
      ],
    },
    secondTower: {
      start: 2,
      end: 6,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 3,
      end: 12,
    },
    multiplicativeOperators: {
      start: 2,
      end: 4,
    },
    prize: 62,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Hard,
  },
  25: {
    fistTower: {
      start: 19,
      end: 27,
      fortuneWheelData: [
        'x21',
        'x19',
        'x25',
        'x20',
        'x23',
        'x22',
        'x24',
        'x26',
        'x27',
      ],
    },
    secondTower: {
      start: 2,
      end: 6,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 3,
      end: 12,
    },
    multiplicativeOperators: {
      start: 2,
      end: 4,
    },
    prize: 64,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Hard,
  },
  26: {
    fistTower: {
      start: 19,
      end: 27,
      fortuneWheelData: [
        'x25',
        'x20',
        'x23',
        'x22',
        'x24',
        'x21',
        'x19',
        'x26',
        'x27',
      ],
    },
    secondTower: {
      start: 2,
      end: 6,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 2,
      end: 13,
    },
    multiplicativeOperators: {
      start: 2,
      end: 4,
    },
    prize: 66,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Hard,
  },
  27: {
    fistTower: {
      start: 19,
      end: 27,
      fortuneWheelData: [
        'x25',
        'x23',
        'x22',
        'x24',
        'x21',
        'x19',
        'x20',
        'x26',
        'x27',
      ],
    },
    secondTower: {
      start: 2,
      end: 6,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 2,
      end: 13,
    },
    multiplicativeOperators: {
      start: 2,
      end: 4,
    },
    prize: 68,
    attempts: 6,
    difficulty: LEVEL_DIFFICULTY.Hard,
  },
  28: {
    fistTower: {
      start: 20,
      end: 28,
      fortuneWheelData: [
        'x25',
        'x22',
        'x24',
        'x21',
        'x28',
        'x20',
        'x23',
        'x26',
        'x27',
      ],
    },
    secondTower: {
      start: 2,
      end: 6,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 2,
      end: 13,
    },
    multiplicativeOperators: {
      start: 2,
      end: 4,
    },
    prize: 70,
    attempts: 7,
    difficulty: LEVEL_DIFFICULTY.Hard,
  },
  29: {
    fistTower: {
      start: 20,
      end: 28,
      fortuneWheelData: [
        'x22',
        'x24',
        'x21',
        'x28',
        'x20',
        'x25',
        'x23',
        'x26',
        'x27',
      ],
    },
    secondTower: {
      start: 3,
      end: 7,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 2,
      end: 13,
    },
    multiplicativeOperators: {
      start: 2,
      end: 4,
    },
    prize: 72,
    attempts: 7,
    difficulty: LEVEL_DIFFICULTY.Hard,
  },
  30: {
    fistTower: {
      start: 22,
      end: 30,
      fortuneWheelData: [
        'x22',
        'x24',
        'x30',
        'x28',
        'x20',
        'x25',
        'x23',
        'x26',
        'x27',
      ],
    },
    secondTower: {
      start: 3,
      end: 7,
      fortuneWheelData: ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    },
    simpleOperators: {
      start: 2,
      end: 13,
    },
    multiplicativeOperators: {
      start: 2,
      end: 5,
    },
    prize: 75,
    attempts: 7,
    difficulty: LEVEL_DIFFICULTY.Hard,
  },
}

export const LEVEL_NAMES: Record<LevelId, string> = {
  1: 'New York',
  2: 'Los Angeles',
  3: 'Chicago',
  4: 'Dallas',
  5: 'Houston',
  6: 'Miami',
  7: 'Atlanta',
  8: 'Washington',
  9: 'Philadelphia',
  10: 'Phoenix',
  11: 'London',
  12: 'Paris',
  13: 'Dublin',
  14: 'Barcelona',
  15: 'Rome',
  16: 'Amsterdam',
  17: 'Berlin',
  18: 'Kyiv',
  19: 'Lviv',
  20: 'Donetsk',
  21: 'Tokyo',
  22: 'Jakarta',
  23: 'Manila',
  24: 'Seoul',
  25: 'Bangkok',
  26: 'Osaka',
  27: 'Ho Chi Minh City',
  28: 'Taipei',
  29: 'Kuala Lumpur',
  30: 'Yangon',
}

export const COUNTRY_LIST: Array<Country> = [
  {
    id: 'USA',
    name: 'United States',
    code: '+1',
    flag: USAFlagIcon,
  },
  {
    id: 'CA',
    name: 'Canada',
    code: '+1',
    flag: CAFlagIcon,
  },
]
