export const getLevelIcon = (level: number) => {
  switch (level) {
    case 1:
      return require('../../assets/images/levels/1/icon.png')
    case 2:
      return require('../../assets/images/levels/2/icon.png')
    case 3:
      return require('../../assets/images/levels/3/icon.png')
    case 4:
      return require('../../assets/images/levels/4/icon.png')
    case 5:
      return require('../../assets/images/levels/5/icon.png')
    case 6:
      return require('../../assets/images/levels/6/icon.png')
    case 7:
      return require('../../assets/images/levels/7/icon.png')
    case 8:
      return require('../../assets/images/levels/8/icon.png')
    case 9:
      return require('../../assets/images/levels/9/icon.png')
    case 10:
      return require('../../assets/images/levels/10/icon.png')
    case 11:
      return require('../../assets/images/levels/11/icon.png')
    case 12:
      return require('../../assets/images/levels/12/icon.png')
    case 13:
      return require('../../assets/images/levels/13/icon.png')
    case 14:
      return require('../../assets/images/levels/14/icon.png')
    case 15:
      return require('../../assets/images/levels/15/icon.png')
    case 16:
      return require('../../assets/images/levels/16/icon.png')
    case 17:
      return require('../../assets/images/levels/17/icon.png')
    case 18:
      return require('../../assets/images/levels/18/icon.png')
    case 19:
      return require('../../assets/images/levels/19/icon.png')
    case 20:
      return require('../../assets/images/levels/20/icon.png')
    case 21:
      return require('../../assets/images/levels/21/icon.png')
    case 22:
      return require('../../assets/images/levels/22/icon.png')
    case 23:
      return require('../../assets/images/levels/23/icon.png')
    case 24:
      return require('../../assets/images/levels/24/icon.png')
    case 25:
      return require('../../assets/images/levels/25/icon.png')
    case 26:
      return require('../../assets/images/levels/26/icon.png')
    case 27:
      return require('../../assets/images/levels/27/icon.png')
    case 28:
      return require('../../assets/images/levels/28/icon.png')
    case 29:
      return require('../../assets/images/levels/29/icon.png')
    case 30:
      return require('../../assets/images/levels/30/icon.png')
    default:
      return require('../../assets/images/levels/1/icon.png')
  }
}
